// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVUg9WlXGrLeQErvh6zr5ccaOhRQRE1Yg',
    appId: '1:385682929993:android:f44983ccbe6f5cda54c298',
    messagingSenderId: '385682929993',
    projectId: 'projectrc-ecf5f',
    databaseURL: 'https://projectrc-ecf5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectrc-ecf5f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0O3DDcoLkeLJptHUm_PE6_ZvEihqpQcA',
    appId: '1:385682929993:ios:31840b611028fc6c54c298',
    messagingSenderId: '385682929993',
    projectId: 'projectrc-ecf5f',
    databaseURL: 'https://projectrc-ecf5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectrc-ecf5f.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy74Ih_-WAJhvZidIdwhPkIK2ai8XWoLo',
    appId: '1:385682929993:web:79339efcacdf427454c298',
    messagingSenderId: '385682929993',
    projectId: 'projectrc-ecf5f',
    authDomain: 'projectrc-ecf5f.firebaseapp.com',
    databaseURL: 'https://projectrc-ecf5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectrc-ecf5f.firebasestorage.app',
    measurementId: 'G-EPDMEBD2FJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0O3DDcoLkeLJptHUm_PE6_ZvEihqpQcA',
    appId: '1:385682929993:ios:31840b611028fc6c54c298',
    messagingSenderId: '385682929993',
    projectId: 'projectrc-ecf5f',
    databaseURL: 'https://projectrc-ecf5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectrc-ecf5f.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy74Ih_-WAJhvZidIdwhPkIK2ai8XWoLo',
    appId: '1:385682929993:web:4ef8511dbaf985ab54c298',
    messagingSenderId: '385682929993',
    projectId: 'projectrc-ecf5f',
    authDomain: 'projectrc-ecf5f.firebaseapp.com',
    databaseURL: 'https://projectrc-ecf5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectrc-ecf5f.firebasestorage.app',
    measurementId: 'G-DNC2WE11RM',
  );
}
